# docker-compose.yml
version: "3.8"

services:
    db:
        image: postgres:15.2
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: trading
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web:
        build: .
        container_name: fastapi_app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db/postgres

volumes:
    postgres_data:
